#!/usr/bin/env python3
"""
scripts/compile_vocab.py

Merges per-facet YAML files (tags/<facet>.yaml) into a single compiled
tags/tags.yaml for downstream consumers.
Loads facet list from protocol/.

Usage: python3 scripts/compile_vocab.py
"""

import sys
import yaml
from pathlib import Path

# Protocol-driven imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.lib.protocol_loader import get_facets, get_tags_dir

HEADER = "# Auto-generated by compile_vocab.py — do not edit directly.\n# Source of truth: per-facet files (tags/<facet>.yaml)\n"


def main():
    facets = get_facets()
    tags_dir = get_tags_dir()
    output = tags_dir / "tags.yaml"

    all_tags = []
    missing = []

    for facet in facets:
        path = tags_dir / f"{facet}.yaml"
        if not path.exists():
            missing.append(facet)
            continue
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if isinstance(data, list):
            all_tags.extend(data)

    if missing:
        print(f"⚠️  Missing facet files: {missing}")

    # Deterministic sort: by facet, then by tag
    all_tags.sort(key=lambda x: (x.get("facet", ""), x.get("tag", "")))

    with open(output, "w", encoding="utf-8") as f:
        f.write(HEADER)
        yaml.dump(all_tags, f, sort_keys=False, allow_unicode=True, default_flow_style=False)

    print(f"✅ Compiled {len(all_tags)} tags from {len(facets) - len(missing)} facet files → {output}")


if __name__ == "__main__":
    main()
