#!/usr/bin/env python3
"""
scripts/compile_vocab.py

Generates tags/tags.yaml from tags/tags.json (the single source of truth).
Per-facet YAML files are NOT the source — tags.json is.

Usage: python3 scripts/compile_vocab.py
"""

import sys
import yaml
from pathlib import Path

# Protocol-driven imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.lib.protocol_loader import get_tags_dir, load_vocab_json

HEADER = "# Auto-generated by compile_vocab.py from tags/tags.json\n# Source of truth: tags/tags.json\n"


def main():
    tags_dir = get_tags_dir()
    output = tags_dir / "tags.yaml"

    vocab = load_vocab_json()
    all_tags = vocab.get("tags", [])

    # Deterministic sort: by facet, then by tag
    all_tags.sort(key=lambda x: (x.get("facet", ""), x.get("tag", "")))

    with open(output, "w", encoding="utf-8") as f:
        f.write(HEADER)
        yaml.dump(all_tags, f, sort_keys=False, allow_unicode=True, default_flow_style=False)

    print(f"✅ Compiled {len(all_tags)} tags from tags.json → {output}")


if __name__ == "__main__":
    main()
